[package]
name = "hw_04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
csv = "1.3.0"
flume = "0.11.0"
sha256 = "1.4.0"
slug = "0.1.4"
unicode-segmentation = "1.10.1"
