[package]
name = "hw_02_syntax_and_variables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.4.0"
slug = "0.1.4"
unicode-segmentation = "1.10.1"
